### ISSUE TITLE
auto reboot gpu watchdog - doesn't work properly

### ISSUE THREAD

**Issue by khunpoum** [doktor83/SRBMiner-Multi#24] opened 2021-03-14 06:03 UTC
version 0.7.0
OS Ubuntu 16.04.05 LTS

on some GPU hashrate decrease at from 66mhs to 2mhs for long time - that sign of GPU is dead also, but reboot script isn't triggered by miner
![image](https://user-images.githubusercontent.com/29778875/111059091-e4e9df00-84a3-11eb-8244-c1a9bdb9eb57.png)
![image](https://user-images.githubusercontent.com/29778875/111059117-0d71d900-84a4-11eb-9e5d-32e80441e430.png)

run script:
```
export GPU_MAX_HEAP_SIZE=100
export GPU_MAX_USE_SYNC_OBJECTS=1
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100
export GPU_MAX_SINGLE_ALLOC_PERCENT=100
export GPU_ENABLE_LARGE_ALLOCATION=100
export GPU_MAX_WORKGROUP_SIZE=1024
cd ~/SRBMiner/0.7.0
./SRBMiner-MULTI --disable-cpu --algorithm autolykos2 \
 --pool <*****> --tls true \
 --wallet <*****> \
 --gpu-errors-alert 20 --forced-shutdown \
 --reboot-script-gpu-watchdog /user/SRBMiner/0.7.0/reboot.sh
```

**Comment by khunpoum** [comment] 2021-03-14 13:51
and here strange behavior of watchdog,
i guess watchdog catch moment of receiving new job from pool and think about it all GPU is dead....
![image](https://user-images.githubusercontent.com/29778875/111071080-95c49e00-84e5-11eb-9390-0488e6397fd0.png)

**Comment by doktor83** [comment] 2021-03-16 04:04
Right now a GPU is considered dead when its not reporting that it is working for minimum 90 sec. When a job is received on autolykos all the workers get stopped, that's the 0hs, and it is normal, but the GPU0 dead is prob a bug, i will try to find it.

**Comment by doktor83** [comment] 2021-03-26 19:40
Simulated GPU crash by setting core clock too low while mining, and miner detected the card die, and restarted miner.
I will close this issue as i can't reproduce your exact issue.

![4141](https://user-images.githubusercontent.com/6808360/112684403-4aaa7380-8e73-11eb-9870-57abf203b1c4.jpg)

**Closed by doktor83** 2021-03-26 19:40 UTC
